### ISSUE TITLE
Server-Status

### ISSUE THREAD

**Issue by dabenzel** [moritzruth/rustplatz#1]
Nice-To-Have wäre noch ein Server-Status (Server aktuell Online/Offline). 
Hätte das in nem PR gemacht, habe aber mit Vue/JS noch nie gearbeitet. Falls das okay wäre, würde ich das Projekt mal Forken und es versuchen.

**Comment by moritzruth** [comment]
Gerne, ich muss dich aber warnen: Ich habe mir nicht besonders viel Mühe mit dem CSS gegeben, Farben sind also z. B. nicht zentral an einer Stelle definiert, sondern über mehrere Dateien verteilt.
Ansonsten viel Glück!

**Comment by moritzruth** [comment]
Es wird übrigens Vue 3 (noch relativ neu) verwendet. Die Dokumentation findest du hier: https://v3.vuejs.org/guide/introduction.html

**Comment by dabenzel** [comment]
https://github.com/dabenzel/rustplatz/commit/b6fa62bb771e0d483680452b860a458fc5d60978

Ist das grundlegend so korrekt?

**Comment by moritzruth** [comment]
Die Dateien in `functions` sind serverseitig (mit Netlify Functions). Der Status muss aber eigentlich nicht vom Server abgerufen werden, also brauchst du auch keine Function dafür.
Ansonsten sieht alles ganz gut aus. Erstell am besten schon mal einen Draft-PR, dann kann ich Vorschläge kommentieren.
