### ISSUE TITLE
Ingame-Namen (falls abweichend) anzeigen

### ISSUE THREAD

**Issue by toxic2302** [moritzruth/rustplatz#6]
Hey. Ich habe mich beim Bearbeiten der teams gefragt, warum du bei manchen ingame Namen speicherst, obwohl diese gar nicht an die Öffentlichkeit getragen werden. Mein Vorschlag wäre das man für alle die ingame Namen aufnimmt und dann neben dem Namen auf der Card anzeigt.

Ist nur so eine Idee, weil ich mich selber schon bei manchen Charakteren gefragt habe, welcher Streamer dahinter steckt. ;)

Beste Grüße

**Comment by moritzruth** [comment]
Die Ingame-Namen speichere ich, da damit eigentlich abgerufen wird, welche Spieler gerade tatsächlich auf dem Rust-Server online sind. Leider geht das seit ein paar Tagen nicht mehr, da was an der Firewall geändert wurde. Ich warte diesbezüglich noch auf eine Antwort von einem Server-Admin.

Wenn in der Liste nur ein String statt einem Object ist, heißt das, dass alle drei Namen (Twitch, Ingame und Anzeigename) gleich sind.

> Mein Vorschlag wäre das man für alle die ingame Namen aufnimmt und dann neben dem Namen auf der Card anzeigt.

Ich werde mal schauen, ob ich das irgendwie umsetzen kann. Eigentlich ist nämlich kein Platz mehr in den Cards :D

**Comment by toxic2302** [comment]
> Wenn in der Liste nur ein String statt einem Object ist, heißt das, dass alle drei Namen (Twitch, Ingame und Anzeigename) gleich sind.

Jap das hab ich mir schon gedacht.

> Ich werde mal schauen, ob ich das irgendwie umsetzen kann. Eigentlich ist nämlich kein Platz mehr in den Cards :D

Ja irgendwie nicht mehr so viel Platz aber es wäre auf jeden Fall ein Gewinn für den Nutzer. ;)
